web:
  build: .
  links:
    - postgres
  environment:
    VIRTUAL_HOST: iotlogic.kkiro.kr
    VIRTUAL_PORT: 8000
postgres:
  image: yoo2001818/armv7-postgresql
  environment:
    DB_NAME: iotlogic
    DB_USER: iotlogic
    DB_PASS: iotlogicpostgres
    PSQL_TRUST_LOCALNET: 1
